# Generated by Django 4.2.3 on 2023-07-22 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='slug',
        ),
        migrations.AddField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='secret_key',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
